### ISSUE TITLE
1.9.7 and develop branch: editing organization: oops - you need to select at least one item

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket#2009]
When you navigate to the organization directory and edit an organization this message appears once for a very short time. This happens in version 1.9.7 and the develop branch. You can reproduce it with the following steps:

1) navigate to the user directory:
![s1](https://cloud.githubusercontent.com/assets/5539456/7468299/063ffad4-f307-11e4-8b39-4dbe28aa0ba0.jpg)
2) navigate to the organization directory and click on an organization to edit it:
![s2](https://cloud.githubusercontent.com/assets/5539456/7468382/2abb3706-f308-11e4-8c4e-7b390c1eefec.jpg)

3) change a value and click on "update organization"
![s3](https://cloud.githubusercontent.com/assets/5539456/7468311/28d71078-f307-11e4-8d35-a7f5e614d130.jpg)

4) the message appears:
![s4](https://cloud.githubusercontent.com/assets/5539456/7468410/7f69bf7a-f308-11e4-9ae7-6c0abf4d2610.jpg)

The message will only appear just one second and after that it only appears again when you navigate to a different area of osticket and navigate back to the organization directory and edit an organization. It seems to have no negative effect, but probably you should now it anyway.

**Comment by agalloway83** [comment]
I've also seen this same message when selecting a user from the user search when creating a new ticket.

**Comment by nanohard** [comment]
Using 1.9.7.
When 'updating' an organization:
I don't see that message, but probably related to the fact that the "Fields" tab in that pop-up does not update in the database when values are changed and "Update Organization" is clicked; however, the "Settings" tab does update when the info is changed.

**Comment by greezybacon** [comment]
I've noticed this too. I know part of this issue is cleaned up in the `develop` branch to be released soon. I'll check on the spurious popup

**Comment by mfelber** [comment]
@agalloway83 Interesting, that seem to be the same issue. I can reproduce it again only when I navigate to a different section, then to the ticket area, directly open a ticket, add a user from the search and click on continue, then the same pop up appears.

**Comment by mfelber** [comment]
@nanohard I think that is a different issue what you describe. Do you mean the behavior that is described in #1997? This exists already in version 1.9.4. The issue described here starts with version 1.9.7 and is also reproducible with the actual develop branch.

**Comment by nanohard** [comment]
@mfelber Yes, thanks. I thought this was related.

**Comment by greezybacon** [comment]
I believe this is fixed in v1.9.8 in ec799d8f7c3081871aee941054ef3156176878c9. Can anyone confirm?

**Comment by mfelber** [comment]
@greezybacon I have made just a fresh install of v1.9.8 and the oops message still appears..

**Comment by infectormp** [comment]
this bug present in 1.10-dpr

**Comment by infectormp** [comment]
a have this issue in 1.9.9 when editing user info

**Comment by infectormp** [comment]
this happening from time to time

**Comment by JediKev** [comment]
I cannot replicate this issue with the latest, supported versions (`v1.12.5` and `v1.14.1`). Please reopen if still an issue with `1.12.x` or `1.14.x`.
