### ISSUE TITLE
1.10 Lazy lock issue

### ISSUE THREAD

**Issue by kest874** [osTicket/osTicket#2343]
Not sure why exactly, but if I try to edit a ticket I get the "Your lock is expiring soon.
The lock you hold on this ticket will expire soon. Would you like to renew the lock? prompt.  I click "Renew" and it spins forever.

If I submit the reply I get the " This action requires a lock. Please try again" alert.  Any idea of the cause?

**Comment by jdelhome3578** [comment]
I noticed the same thing.

**Comment by jdelhome3578** [comment]
The lazy lock drop down also covers the ticket floating bar.

**Comment by greezybacon** [comment]
> The lazy lock drop down also covers the ticket floating bar.

That's the idea. It's like a popup but doesn't hijack the screen

**Comment by greezybacon** [comment]
Can anyone try the patch in #2351?

**Comment by jdelhome3578** [comment]
Renews once but not a second time. The drop down is still there as soon as I start to type in the response box. Is this intended?

**Comment by kest874** [comment]
Same result as the original issue.

I does create a lock int he database:

![image](https://cloud.githubusercontent.com/assets/12860950/9038237/7bb8096c-39b8-11e5-8b07-82e6fe6ea2f0.png)

![image](https://cloud.githubusercontent.com/assets/12860950/9038271/b606d8f0-39b8-11e5-859b-a458e50c3df3.png)

![image](https://cloud.githubusercontent.com/assets/12860950/9038306/f6c81a02-39b8-11e5-9f2a-966554f4b097.png)

**Comment by kest874** [comment]
I get this behavior with a brand new install, clone develop-next then setup (clean DB) and try to post a reply to the pre-loaded ticket.

**Comment by greezybacon** [comment]
We merged the patch in #2351 today. Perhaps it had some bearing on the problem

**Comment by jdelhome3578** [comment]
Just tested from the tip of `develop-next` and I still have the `This action requires a lock. Please try again` message.

**Comment by jdelhome3578** [comment]
I turned off `Collision Avoidance` and receive this message `Unable to lock the ticket.` now when trying to reply to a ticket and posting a note.

**Comment by kest874** [comment]
I can now start typing the reply and when I hit "Post Reply" I get the following:

![image](https://cloud.githubusercontent.com/assets/12860950/9096265/b350373a-3b81-11e5-9ee9-eb56e740d30c.png)

Clicking "OK" I get:

![image](https://cloud.githubusercontent.com/assets/12860950/9096290/d17f2bda-3b81-11e5-826f-3cfe5f6be5a2.png)

No matter what I get the same lock message.

I noticed that the lock table does not have an entry in it.

Setting Collision Avoidance Duration: to 0 lets me work around the issue now as before it did not.  

Anything I can do to help troubleshoot this issue let me know?

**Comment by jdelhome3578** [comment]
Just tested from the tip of `develop-next` and I still have the `This action requires a lock. Please try again` message. Windows Based IIS 7 php5.5.23 mySQL5.6.11

**Comment by kest874** [comment]
With the latest commits even with the collision avoidance set to 0 I get:

![image](https://cloud.githubusercontent.com/assets/12860950/9112211/d97168c6-3c12-11e5-836c-6c721c9e5e1f.png)


I also tested with a clean slate starting with 1.9.11 and upgrading to 1.10 with the same result.

**Comment by balojs** [comment]
+1

**Comment by jdelhome3578** [comment]
Just tested from tip with 1.10 rc1 + 115 commits, still have error `This action requires a lock. Please try again`

**Comment by greezybacon** [comment]
@jdelhome3578 I disagree. I feel pretty confident the lock system is working. Perhaps you need to clear your browser cache after updating the codebase

**Comment by jdelhome3578** [comment]
I cleared cache. Still having issue. Windows Based IIS 7 php5.5.23 mySQL5.6.11 Chrome Browser

**Comment by jdelhome3578** [comment]
@greezybacon 

1. I open the ticket
2. I start to type in the response box
3. Your lock is expiring soon. Drops down.
4. I click Post Reply
5. This action requires a lock. Please try again.

Repeat over and over again. I have tried a new server, new install, clear the cache.

**Comment by kest874** [comment]
@greezybacon  

I can duplicate this exactly, not really sure why it isn't working.  This happens with a green install as well with all develop-next commits.

**Comment by balojs** [comment]
me too @kest874

**Comment by greezybacon** [comment]
Are you guys using the tip of `develop-next` or the rc1 release?

**Comment by jdelhome3578** [comment]
I have been using the tip of develop-next

**Comment by balojs** [comment]
develop-next

**Comment by jdelhome3578** [comment]
Step by step images

Before Lock:
![image](https://cloud.githubusercontent.com/assets/5774055/9252398/1e6784cc-41a6-11e5-976f-722f3fb9c219.png)

![image](https://cloud.githubusercontent.com/assets/5774055/9252451/724a844a-41a6-11e5-8a1c-17836dded2c6.png)

After Lock before post:
![image](https://cloud.githubusercontent.com/assets/5774055/9252531/d1df88c4-41a6-11e5-9023-65ef57e51ef6.png)

![image](https://cloud.githubusercontent.com/assets/5774055/9252576/084b77b0-41a7-11e5-816a-f55bc66fa5c5.png)

![image](https://cloud.githubusercontent.com/assets/5774055/9252578/0cd36ec8-41a7-11e5-9cef-f4a3f216a01f.png)

After post:
![image](https://cloud.githubusercontent.com/assets/5774055/9252622/6b50abfa-41a7-11e5-8073-336ad0c90ec6.png)

![image](https://cloud.githubusercontent.com/assets/5774055/9252627/6fa05890-41a7-11e5-81b2-eca3b8d75f8f.png)

**Comment by jdelhome3578** [comment]
@greezybacon 

Step by step images

Before Lock:
![image](https://cloud.githubusercontent.com/assets/5774055/9252398/1e6784cc-41a6-11e5-976f-722f3fb9c219.png)

![image](https://cloud.githubusercontent.com/assets/5774055/9252451/724a844a-41a6-11e5-8a1c-17836dded2c6.png)

After Lock before post:
![image](https://cloud.githubusercontent.com/assets/5774055/9252531/d1df88c4-41a6-11e5-9023-65ef57e51ef6.png)

![image](https://cloud.githubusercontent.com/assets/5774055/9252576/084b77b0-41a7-11e5-816a-f55bc66fa5c5.png)

![image](https://cloud.githubusercontent.com/assets/5774055/9252578/0cd36ec8-41a7-11e5-9cef-f4a3f216a01f.png)

After post:
![image](https://cloud.githubusercontent.com/assets/5774055/9252622/6b50abfa-41a7-11e5-8073-336ad0c90ec6.png)

![image](https://cloud.githubusercontent.com/assets/5774055/9252627/6fa05890-41a7-11e5-81b2-eca3b8d75f8f.png)

**Comment by greezybacon** [comment]
The `time: 0` part is the problem. This has been fixed in `develop-next` with 37a0676b0a6b2d4f94b1cc74276bfe54b5445030

**Comment by jdelhome3578** [comment]
@greezybacon I have all of those commits in my code and I am still having the issue.

**Comment by jdelhome3578** [comment]
@greezybacon Just tested again from the tip of `develop-next` and I am still having the same issue with `time: 0`

**Comment by jdelhome3578** [comment]
@greezybacon Tested 1.10 rc2 and I am still having this issue.

**Comment by greezybacon** [comment]
@jdelhome3578 I'm out of ideas

**Comment by balojs** [comment]
i have same issue (v1.10-rc.2)
![screenshot](https://cloud.githubusercontent.com/assets/3303352/9386656/bb2e1f96-4719-11e5-88cd-258ff5333961.png)

**Comment by jdelhome3578** [comment]
@balojs are you using iis?

**Comment by greezybacon** [comment]
<img width="960" alt="screen shot 2015-08-20 at 10 16 14 am" src="https://cloud.githubusercontent.com/assets/672074/9387121/99edb4f8-4724-11e5-986e-2a4ef468ef49.png">
<img width="1042" alt="screen shot 2015-08-20 at 10 15 56 am" src="https://cloud.githubusercontent.com/assets/672074/9387126/9d35457c-4724-11e5-8aaf-52d87e98b802.png">
<img width="663" alt="screen shot 2015-08-20 at 10 16 27 am" src="https://cloud.githubusercontent.com/assets/672074/9387128/a26e73c4-4724-11e5-9931-e5172a199e3f.png">

What am I doing wrong?

**Comment by jdelhome3578** [comment]
@greezybacon I have collision avoidance duration set to 3 minutes

**Comment by greezybacon** [comment]
@jdelhome3578 you previously posted a screenshot of a JSON payload with `time: 0`. Do you still get such a payload? (It *should* indicated `time: 180`).

**Comment by jdelhome3578** [comment]
@greezybacon I get `time: 0` with collision avoidance duration set to 3 minutes

**Comment by jdelhome3578** [comment]
@greezybacon previous screenshots also had collision avoidance duration set to 3 minutes

**Comment by kaptk2** [comment]
I too have this issue. Was an upgrade from 1.8.3

**Comment by balojs** [comment]
thanks Resolved ( Collision Avoidance Duration: 0)
![screenshot](https://cloud.githubusercontent.com/assets/3303352/9389174/de614db4-4726-11e5-9ecc-82ba90238db2.png)

**Comment by jdelhome3578** [comment]
@balojs I don't consider that a resolution. That just turns Collision Avoidance off.

**Comment by jdelhome3578** [comment]
@greezybacon Any more on this issue?

**Comment by jamesangi** [comment]
I posted on the forum before finding this issue, but I just wanted to say "Me Too."  I'm running a clean install of 1.10rc2. @greezybacon if there is anything I can do to help troubleshoot let me know.

**Comment by greezybacon** [comment]
> @greezybacon I get time: 0 with collision avoidance duration set to 3 minutes

That's really strange

**Comment by greezybacon** [comment]
Ok, I think I found it. If php and the database use differing time zones, the lock always appears to be expired and yields a time remaining of zero. Can anyone try the patch in #2533?

**Comment by jdelhome3578** [comment]
Success `{id: 67, time: 180, code: "FJ1WtR3fm5"}` :+1: :+1:

**Comment by kest874** [comment]
I can confirm this works now as well.

**Comment by colonelpopcorn** [comment]
Works like a charm!

**Comment by theodorocaliari** [comment]
Yep, this work for me too - https://github.com/osTicket/osTicket-1.8/pull/2533 thanks

**Comment by timwhite** [comment]
@greezybacon Even with #2533, this still doesn't work for me. I see the locks created in the DB, the time appears correct. However the json returned still has time:0. I set Collision avoidance time to 0, problem goes away (because it doesn't try and lock), once I set it to anything else it doesn't work.

```
|      11 |        1 | 2016-01-29 18:07:01 | o3OmH9NmnQ | 2016-01-29 18:02:01 |
```
```
{"id":11,"time":0,"code":"o3OmH9NmnQ"}
```

But PHP and MySQL are running in the same timezone (Australia/Brisbane)

**Comment by greezybacon** [comment]
@timwhite did you pull the rest of the changes for v1.10? There were some timezone conversion issues also addressed in various merges

**Comment by timwhite** [comment]
@greezybacon I pulled develop-next, which is currently at 364044e, so I believe all the other TZ stuff should be in it?

**Comment by timwhite** [comment]
Just had a look at the system information page.
```
PHP Settings
date.timezone	 Australia/Brisbane

Database Information and Usage
Timezone	AEST (Interpreted as Australia/Melbourne)
```

Currently we have Daylight savings time in Melbourne, but not Brisbane. However, AEST should not be daylight savings time. If it's interpreting it as Melbourne though, it will be getting daylight savings time, instead of AEST which hasn't got daylight savings.

Any thoughts on how to fix this?

**Comment by greezybacon** [comment]
@timwhite Are you able to change the database time zone? Maybe you should specify "Australia/Brisbane" specifically?

**Comment by ArmgaSys** [comment]
Devs, 

We also encountered the "Unable to lock the ticket" issue using the latest tip.
Turns out there are a couple of issues going on:

Environment
MySQL 5.1
IIS 8
PHP 5.6

**1st Issue**
The ajax.php and dispatcher are not playing nicely with PHP5.6
Under PHP5.6 on IIS, the following error will be fired when the dispatcher returns the JSON payload from ajax.ticket.php
_"PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0"_
This results in the javascript calling the fail: function which displays "Unable to lock the ticket" message. 

Solution & Recommendations
1) Modify the php.ini to set always_populate_raw_post_data to -1
2) Modify the message "Unable to lock the ticket" to state an error has occurred
    The current message is misleading.  It only occurs in an error scenario and has
    nothing to do with someone else having a lock.

**2nd Issue**
The class.lock.php is still susceptible to timezone issues.
This is due to the call to Misc::dbtime and its logic.  Basically, Misc::dbtime is attempting to convert the server time (returned by PHP time()) to the timezone equivalent for MySql.  In more complex configurations, this can fail as the timezones may not be equivalent.

Recommended Solution
Do not rely on the server time.  Ask MySql what it thinks the time is and then compare when checking for Lock expiration and timeouts.  (This solution scales to multiple servers better if you ever want to support a web farm)
-OR-
Do not rely on MySql time.  When inserting the expiration time, calculate the datetime in PHP using the server time and send the calculated value to MySql (I.E. do not use NOW()).  (This solution does not support multiple servers, but will perform better)

**Comment by C4RLOCO** [comment]
Hi!
I am having issues with the lazy lock as well. Just upgraded to v1.10-RC3

Server Information
osTicket Version	v1.10-rc.3 (907ec36)
Web Server Software	Apache
MySQL Version	5.5.45
PHP Version	5.6.22

 When editing a ticket I get the "Your lock is expiring soon.
The lock you hold on this ticket will expire soon. Would you like to renew the lock? prompt. I click "Renew" and it spins forever.

If I submit the reply I get the " This action requires a lock. Please try again" alert.

**Comment by fictionedge** [comment]
Hi
I'm having the same problem with 1.10 final version too.
I've already populated the timezone table in the database, set the database time zone, set the timezone in the System Settings and Preferences and in the users profile to be the same but I still get the same error.

**Comment by demogar** [comment]
Still present on the latest available version. Had to turn off the lazy lock functionality.

**Comment by iHunt101** [comment]
Got this one too. Can we have a check box like for this functionalty to turn if off if we dont need it? @greezybacon

**Comment by dogatemycomputer** [comment]
+1

**Comment by bedo2991** [comment]
I am getting the same problem, fresh installation.
The lock is saved correctly in the database, but the ajax function returns: "time:0" with a CollisionAvoidanceTime set to 3 minutes.

**Comment by adrianoprospero** [comment]
@greezybacon That's it! Thanks!

**Comment by neoand** [comment]
Collision Avoidance equal to 0 zero and is resolved !

**Comment by piojesio** [comment]
The problem has revelead after implementing Fix "unions with sorting on the main query" https://github.com/osTicket/osTicket/commit/e17a9124e7c59d6de7ae21a8e736740b837badec#diff-8a9a2e8df39a44fd83995d685f4eab88
After restoring previous version of class.orm.php file it works properly and sorting still works as well.

**Comment by cocuba** [comment]
Collision Avoidance equal to 0 zero and is resolved for me!

**Comment by boostify-pro** [comment]
This is an old thread but it is still happening 

I'll post this for anyone who faced the same issue, This worked for me:

1- setting server time-zone, php time-zone and database time-zone to same.
2- in osTicket admin, set "Collision Avoidance Duration" to 0

and this fixed the problem.
