### ISSUE TITLE
v1.10-rc.2 Autocomplete not working since upgrade

### ISSUE THREAD

**Issue by slimatic** [osTicket/osTicket#2656]
Since upgrading from 1.9 I have had issues with autocomplete not working in various areas. Not sure what is going on. I cannot add collaborators or Edit a ticket to change the user. What should I be looking at? Is there a fix for this? It was working fine before the upgrade.

@greezybacon please advise.

![image](https://cloud.githubusercontent.com/assets/318846/10518229/6a63c444-732e-11e5-9b35-1b285106b711.png)

**Comment by slimatic** [comment]
I think I have a lead on the bug. I got this DB Error:
![image](https://cloud.githubusercontent.com/assets/318846/10519790/39c1db76-7335-11e5-8f2a-4bcfc6387d50.png)

Looks like this `SELECT` statement has something to do with the lookups:

 [SELECT A1.`id`, A2.`address`, A1.`name` FROM `ost_user` A1 LEFT JOIN `ost_user_email` A2 ON (A1.`id` = A2.`user_id`) GROUP BY A1.`id` ORDER BY __relevance__ DESC LIMIT 25] Unknown column '__relevance__' in 'order clause'

It is failing because of the Unknown column '__relevance__' in 'order clause'.

When I run this `SELECT` statment in the DB it works fine:
SELECT A1.`id`, A2.`address`, A1.`name` FROM `ost_user` A1 LEFT JOIN `ost_user_email` A2 ON (A1.`id` = A2.`user_id`) GROUP BY A1.`id` DESC LIMIT 25

I am a bit of a newbie. Where in the code is this statement being called so I can at least modify the code to fix the issue I am having. Any recommendations on how this can be fixed?

**Comment by protich** [comment]
I'll recommend upgrading to the tip of develop-next branch - which is 134 commits ahead of rc2.

**Comment by protich** [comment]
PR #2657 is also relevant in this context.

**Comment by slimatic** [comment]
I just did a git pull on develop-next branch prior to creating this issue. I am on the latest commit ( a4b057a0cafe2da70977ff7d44b545de465d98ce).

**Comment by protich** [comment]
@slimatic - Thanks for the feedback! I just pushed a fix to develop-next branch (1aaa31).

**Comment by slimatic** [comment]
@protich I tried the commit however there is still a bug. I am still not able to add collaborators or even search for users with the autocomplete - actually it does not work any other way. It attempts to lookup the users but then it looks like it fails immediately with the `Unknown column 'relevance' in 'order clause'`. It seems to me it has something to do with the class.orm.php file. With this feature not working I am unable to use some very important features like changing the user/owner of the ticket.

When I try to add a collaborator it fails with a DB Error 1054 because it tries to run the SQL code below:
SELECT A1.id, A2.address, A1.name FROM ost_user A1 LEFT JOIN ost_user_email A2 ON (A1.id = A2.user_id) GROUP BY A1.id ORDER BY relevance DESC LIMIT 25

If I can find the code that generates this SQL statement and then someone let it ommit the ORDER BY part of the query I believe this might fix the problem.

Error: Unknown column 'relevance' in 'order clause'

**Comment by slimatic** [comment]
@protich Maybe I missed the memo on orgs but did the code change to require users to be in an organization for the search to function properly? I am asking because I never really implemented the use of organizations. I just noticed that when I search for a user in the ticket to add a collaborator it only populates the user if the user is in the one organization that I defined.  I have tested it on several users and they only populate if the user is in the organization. 

Not sure how Organization and User dependency affects search now but I think it will be good to also allow functionality to work for implementations that do not use the Organization feature. I now have to add users to get my search to work. Not a good work around.

@t-oster can you confirm if this is happening for you too? Are you using organizations? Please sare your findings.

**Comment by greezybacon** [comment]
@slimatic are you *sure* you upgraded to the tip of the `develop-next` branch? I can't find where the statement you referenced would be emitted.

**Comment by slimatic** [comment]
@greezybacon Yes, I pulled the latest commit from develop-next. I'm a bit new with git in general so unless I did something that might suggest I pulled the wrong branch, I did a git pull on develop-next and it said it was on the most updated commit for that branch.
