### ISSUE TITLE
Attachment lost while modifying ticket

### ISSUE THREAD

**Issue by OcEtEc** [osTicket/osTicket#2888]
Attachment deleted when a ticket response is edited.
The attachment is no longer visible in the ticket detail view after editing,
but the paperclip icon in the ticket overview windows is still available (that means that there is a file attached).
It is also not possible to re-add the attachment in the ticket edit window, there is no attachment field.
When a response is edited there is a new line in the MySQL database for this entry, but the attachment is still assigned to the old response.
I think this information has to be transferred from the old entry to the new line when a thread with an attachment is changed.

Before editing:
![ticket-error1](https://cloud.githubusercontent.com/assets/16932568/12637226/e04862d4-c593-11e5-8a65-f35cd0398e51.jpg)

Editing the thread:
![ticket-error2](https://cloud.githubusercontent.com/assets/16932568/12637235/f07435e8-c593-11e5-8b7e-7127a4775002.jpg)

After editing:
![ticket-error3](https://cloud.githubusercontent.com/assets/16932568/12637240/fac54258-c593-11e5-9061-0dbb87bf2079.jpg)

**Comment by balojs** [comment]
+1

**Comment by greezybacon** [comment]
This is fixed in 907ec36

**Comment by nobe-vsv** [comment]
Hi,
i´ve faced exactly the same issue at osticket v1.10 stable. The edited tickets lost the attachments and also the edited faq article lost the attachments. I´ve checked the code modification the fix is already included. My System are:
osTicket-Version 	v1.10 (901e5ea) — Aktuell
Server-Software 	Apache
MySQL-Version 	5.5.52
PHP-Version 	5.6.30

could you give me a hint what i have to do? Thanks!

Regards, Norman

**Comment by devi1903** [comment]
Hi,
Just to confirm, fault still exists. Same as Norman. Code as per below already includes the modifications. I have noticed as well that the SLA is also removed from the ticket when it is edited.

`// Replace previous edit --------------------------
$original = $old->getParent();
// Link the new entry to the old id
$entry->pid = $old->pid;
// Drop the previous edit, and base this edit off the original
$old->delete();
$old = $original;
}

// Move the attachments to the new entry
$old->attachments->update(array(
'object_id' => $entry->id
));

// Mark the new entry as edited (but not hidden nor guarded)
$entry->flags = ($old->flags & ~(ThreadEntry::FLAG_HIDDEN | ThreadEntry::FLAG_GUARDED))
| ThreadEntry::FLAG_EDITED;

// Guard against deletes on future edit if requested. This is done
// if an email was triggered by the last edit. In such a case, it
// should not be replaced by a subsequent edit.
if ($guard)
$entry->flags |= ThreadEntry::FLAG_GUARDED;
`

**Comment by furetto** [comment]
any news on this bug?

**Comment by devi1903** [comment]
Unfortunately no news, issue still not resolved

**Comment by mtitter** [comment]
Any movement on this issue? Still having this happen to us on v1.10.1

**Comment by luiizfenix** [comment]
issue still exist on v1.10.1 currently trying to fix it without success.

Also radio button gets reset even if set to "not editable by agent" 

any news from the more experienced here? @ntozier @JediKev @greezybacon

**Comment by devi1903** [comment]
I have also noted that date fields add one day each time you edit and save the ticket without you changing the date, its clear that these faults on edit are quite broad

**Comment by cbiere** [comment]
This bug is NOT fixed. I'm using the Knowledge Base as central point for all documentation. If the attached documents are not safe there, this feature is complete and utter useless. This should be disabled until it is fixed.

**Comment by alexdjachenko** [comment]
I have the same problem.
Version 10.10.1 + Plugin "Attachments on the filesystem"

**Comment by F3000** [comment]
I have tested it with 1.10.1 


MySQL Version | 5.5.56
PHP Version | 5.4.16
Np plugins 

I have edited and dont lost the attachment

**Comment by devi1903** [comment]
@F3000 i can confirm this bug is not fixed. Unfortunately at this stage this bug is making OSTicket unusable for setups that require file attachments as data is not secure. When reproducing this fault it must be noted that if you edit tickets as the same user this fault does not exist. This only exists when a user creates a ticket and then a different user edits the ticket. When the different user edits the ticket the attachment gets removed. Also note that the SLA gets unset and all date fields go back by a number of days. Only if the user selects these fields themselves or deletes and re-uploads an attachment does it remain in place after the ticket is saved. I would not be surprised if the knowledge base issue is linked to exactly the same bug.

**Comment by ntozier** [comment]
@protich @greezybacon @JediKev 
This has been confirmed as still an issue.
Please reopen

**Comment by rockmanchile** [comment]
not a good sign from osticket developers...this issue has over a year now with no easy or quick workaround...i think i going back to 1.9 until the next stable version...1.10 is still very buggy...

**Comment by iantic** [comment]
Still not fixed, please reopen

**Comment by JediKev** [comment]
@iantic 

This is a very old and outdated report. Please create a new Issue filling out the entire Issue Template.

Cheers.
