### ISSUE TITLE
DB Error #1054 after using Inline Editor to Update custom field (and DB Error #1146 and #1064)

### ISSUE THREAD

**Issue by pmb399** [osTicket/osTicket#4801]
### Description
I created a custom field in the ticket form that I want to update in a specific ticket. But I get the following error message immediately after entering the value into the custom field and saving it (using the Inline Editor):

[INSERT INTO `eiay_ticket__cdata` SET `field`='Fulda', `ticket_id`= 131 ON DUPLICATE KEY UPDATE `field`='Fulda']

Unknown column 'field' in 'field list'

---- Ablaufverfolgung ----<br />
#0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1054', '[INSERT INTO `e...')<br />
#1 (root)/include/class.dynamic_forms.php(332): db_query('INSERT INTO `ei...')<br />
#2 (root)/include/class.dynamic_forms.php(344): DynamicForm::updateDynamicDataView(Object(DynamicFormEntryAnswer), Array)<br />
#3 (root)/include/class.signal.php(98): DynamicForm::updateDynamicFormEntryAnswer(Object(DynamicFormEntryAnswer), Array)<br />
#4 (root)/include/class.orm.php(684): Signal::send('model.updated', Object(DynamicFormEntryAnswer), Array)<br />
#5 (root)/include/class.dynamic_forms.php(1458): VerySimpleModel->save(true)<br />
#6 (root)/include/class.forms.php(1377): DynamicFormEntryAnswer->save(true)<br />
#7 (root)/include/class.ticket.php(3340): FormField->save()<br />
#8 (root)/include/ajax.tickets.php(522): Ticket->updateField(Object(SimpleForm), Array)<br />
#9 (root)/include/class.dispatcher.php(145): TicketsAjaxAPI->editField('131', '36')<br />
#10 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('131/field/36/ed...', Array)<br />
#11 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('131/field/36/ed...', Array)<br />
#12 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/tickets/131/fi...', NULL)<br />
#13 (root)/scp/ajax.php(289): Dispatcher->resolve('/tickets/131/fi...')<br />
#14 {main}

### Comment
It seems strange that the sql query is trying to set the value in "field" because the corresponding column in the MySQL DB is called "field_36".
Note that this behaviour only applies to changes made using the Inline Editor. It works properly when being changed while in the ticket editing mode.

### Steps to Reproduce

1. Go to desired ticket
2. Click on custom field and wait for the popup editor to open
3. add/edit value
4. save

**Expected behavior:** 
The value of the custom field is written to the database.

**Actual behavior:**
You get the error message above.
Refreshing the database in MySQL reveals that the table "ticket__cdata" has been deleted. After clicking on a queue in osTicket, the table gets rebuild. However, I sometimes encountered this #1146 error message shortly after (but not alwayas):

[SELECT COUNT(DISTINCT CASE WHEN A8.`field_36` = 'Fulda' THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND NOT A8.`field_36` = 'Fulda' THEN A1.`ticket_id` END) AS `q1`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND NOT A8.`field_36` = 'Fulda' AND A2.`state` = 'open' AND NOT A8.`field_36` = 'Fulda' AND A1.`isanswered` = '0' THEN A1.`ticket_id` END) AS `q2`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (1) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' AND (A1.`team_id` IN (1) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' AND A1.`staff_id` IN (1) THEN A1.`ticket_id` END) AS `q6`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-03-14 00:00:00' AND '2019-03-14 23:59:59' THEN A1.`ticket_id` END) AS `q9`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND NOT A8.`field_36` = 'Fulda' AND A2.`state` = 'open' AND NOT A8.`field_36` = 'Fulda' AND A1.`isanswered` = '1' THEN A1.`ticket_id` END) AS `q3`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (1) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' AND (A1.`team_id` IN (1) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' AND NOT A1.`staff_id` IN (1) THEN A1.`ticket_id` END) AS `q7`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-03-13 00:00:00' AND '2019-03-13 23:59:59' THEN A1.`ticket_id` END) AS `q10`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND NOT A8.`field_36` = 'Fulda' AND A2.`state` = 'open' AND NOT A8.`field_36` = 'Fulda' AND A1.`isoverdue` = '1' THEN A1.`ticket_id` END) AS `q4`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (1) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q5`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-03-11 00:00:00' AND '2019-03-17 23:59:59' THEN A1.`ticket_id` END) AS `q11`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' THEN A1.`ticket_id` END) AS `q8`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-03-01 00:00:00' AND '2019-03-31 23:59:59' THEN A1.`ticket_id` END) AS `q12`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-01-01 00:00:00' AND '2019-03-31 23:59:59' THEN A1.`ticket_id` END) AS `q13`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-01-01 00:00:00' AND '2019-12-31 23:59:59' THEN A1.`ticket_id` END) AS `q14` FROM `eiay_ticket` A1 JOIN `eiay_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `eiay_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `eiay_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `eiay_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `eiay_team` A6 ON (A4.`object_type` = 'E' AND A4.`object_id` = A6.`team_id`) LEFT JOIN `eiay_department` A7 ON (A4.`object_type` = 'D' AND A4.`object_id` = A7.`id`) LEFT JOIN `eiay_ticket__cdata` A8 ON (A1.`ticket_id` = A8.`ticket_id`) WHERE (A2.`state` = 'open' AND (A1.`staff_id` = 1 OR A5.`staff_id` = 1 OR A1.`team_id` IN (1) OR A6.`team_id` IN (1))) OR A1.`dept_id` IN (1) OR A7.`id` IN (1)]

Table 'db264979x2766149.eiay_ticket__cdata' doesn't exist

---- Ablaufverfolgung ----<br />
#0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1146', '[SELECT COUNT(D...')<br />
#1 (root)/include/class.orm.php(3454): db_query('SELECT COUNT(DI...', true, true)<br />
#2 (root)/include/class.orm.php(3501): MySqlExecutor->execute()<br />
#3 (root)/include/class.orm.php(2085): MySqlExecutor->getArray()<br />
#4 (root)/include/class.orm.php(2035): HashArrayIterator->{closure}()<br />
#5 (root)/include/class.orm.php(2014): CallbackSimpleIterator->next()<br />
#6 (root)/include/class.orm.php(2023): CallbackSimpleIterator->rewind()<br />
#7 (root)/include/class.orm.php(1695): CallbackSimpleIterator->valid()<br />
#8 (root)/include/class.orm.php(1705): CachedResultSet->fillTo(9223372036854775807)<br />
#9 (root)/include/class.orm.php(1328): CachedResultSet->asArray()<br />
#10 (root)/include/class.orm.php(1351): QuerySet->all()<br />
#11 (root)/include/class.search.php(922): QuerySet->one()<br />
#12 (root)/include/ajax.search.php(397): SavedQueue::counts(Object(StaffSession), true, Array)<br />
#13 (root)/include/class.dispatcher.php(145): SearchAjaxAPI->collectQueueCounts()<br />
#14 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('counts', Array)<br />
#15 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('counts', Array)<br />
#16 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/queue/counts', NULL)<br />
#17 (root)/scp/ajax.php(289): Dispatcher->resolve('/queue/counts')<br />
#18 {main}

## Other behaviour
Creating a custom queue that depends on the custom field does not work anymore. No tickets will be displayed in the queue. Also, I sometimes get an DB #1064 error message that I cannot reproduce.

### Versions

![Screenshot from 2019-03-15 23-05-28](https://user-images.githubusercontent.com/20231767/54470986-df534480-4776-11e9-860e-ad8474bd1e78.png)

Thanks, Patrick

**Comment by JediKev** [comment]
@pmb399

You don’t have the `ticket__cdata` table which is weird because you should always have one (it gets recreated automatically). That’s why you get the COUNT error and most likely why custom queues don’t work with custom fields.

As for the unknown column in field list error I don’t know what’s causing that. Was this a new install, upgrade? If this was an upgrade, did it go through successfully or were there errors? Do you have any mods in place or third party themes installed?

Also, did anyone mess with tables in the db? If this was an upgrade, do you have a backup of before the upgrade? If so, do you have a `ticket__cdata` table?

Cheers.

**Comment by pmb399** [comment]
Let me clarify: the ticket__cdata table does exist before I do any changes to the custom field. After I change a custom field with the inline Editor and refresh the db in phpmyadmin the ticket__cdata table is gone until I click on some queue in osTicket (GUI). The table then gets recreated with all the previous values. Not sure if this behaviour is intended or not, I just noticed. No modifications to the db tables were made at any time.

This was a upgrade from 1.10.5 but there were no error message during the upgrade process. It said that I upgraded it to the new version successfully. Also, I just checked the db before the upgrade and there is ticket__cdata table in the db.

I have a German language pack and the plugin "attachments on the file system" installed.

Since I only found out recently about that inline editor, I used to change all fields via the edit button (that opens the edit mode) in the ticket.The custom queues were working as intended. I just encountered this strange behaviour after updating a field with the inline editor for the first time in that installation (followed by the error message above).

Cheers!

**Comment by JediKev** [comment]
@pmb399

What type of field is the custom field, what’s the configuration of the field etc. I’m going to try to replicate this as I’ve never encountered this error before.

Cheers.

**Comment by kulczakk** [comment]
I have a similar issue on a fresh instance so I doubt it's upgrade-related.

![image](https://user-images.githubusercontent.com/46870635/54477101-d90ba980-4804-11e9-9016-b819b66b8b56.png)


![image](https://user-images.githubusercontent.com/46870635/54477087-bf6a6200-4804-11e9-9d8a-509f4278800d.png)

**Comment by pmb399** [comment]
@JediKev:

The field is setup in the "Ticket (Details)" form. It's configured as short answer, has no variable assigned (but thats not the issue when I checked). Size is 16, maximum length 30, no validator etc. is set. The field is active and visible to users and agents, not a mandatory field, editable for users and agents. Data integrity checkbox under settings tab is off.

Thanks!

**Comment by pmb399** [comment]
I mentioned above that after encountering this DB 1054 error, custom build queues would not work properly. The reason for this behaviour was that I was using a condition for my queue to filter such that "some_custom_field" is not equal to "value". 

As I started to analyse the ticket__cdata table, I noticed that new tickets which do not have a value set for the custom field were created with an empty value (but were not (!) set to Null). All existing tickets in the ticket__cdata table which did not have a value set for the custom field, however, were set to Null. So, replacing that Null with a value of ' ' solved the issue with the custom queue for me. Not entirely sure why that is.

I just thought I would let you know, in case somebody else has similar issues. I still have no idea what the deal with that inline editor is, though...

Cheers!

**Comment by JediKev** [comment]
@pmb399

Ah great catch. That’ll definitely help us in tracking the issue.

Cheers.

**Comment by JediKev** [comment]
@pmb399

Have you had a chance to use the latest pull from develop-next branch to see if these issues occur with the latest codebase? v1.11 on our site is the stable release from a minute ago (can’t exactly remember when we released and I’m on my phone). The develop-next branch includes the latest bug fixes we’ve been pushing since the stable release. So maybe this includes a fix to your issues already.

Cheers.

**Comment by pmb399** [comment]
@JediKev 

I just installed the latest develop-next version. I still get that DB 1054 error after using the Inline Editor.

In this new installation:
- I get the DB 1054 error after using the inline editor. The tickets__cdata table gets rebuild after I encounter this error. All empty values in the initial table are being set to Null in the rebuild table. Even though you get the error message, the custom field that I want to update is actually updated in the table and thus the value is stored in the correct place in tickets__cdata!

- I also tested the behaviour of tickets__cdata after applying any modifications to the forms under Manage/Forms. As you apply changes, the table gets rebuild and, again, all empty values are replaced with Null.

Henceforth, I think there are two issues here: one due to the inline editor and one due to the rebuild of the tickets__cdata table.

Cheers!

**Comment by JediKev** [comment]
@pmb399 

I think it's only the `__cdata` rebuild but it could be both. Will investigate this.

Cheers.

**Comment by JediKev** [comment]
@pmb399 

Okay, so super strange find here...I tried testing this using your exact steps using latest `develop-next` (from today), PHP 5.6, and Apache and I'm not able to replicate the issue. I then thought that it could possibly be PHP 7+ related so I tested again using latest `develop-next` from today, PHP 7.2, and NGINX and I was still not able to replicate your issue. My values in both databases are created with empty values instead of `NULL`.

At this point I'm uncertain what's going on with your install as I'm using same setup as you minus PHP 7.0 and installed language pack. I do have langs installed just not applied. When you installed osTicket, did you install using a language pack (ie. did you install under a different language) or did you install the language packs afterwards?

Any other information you can provide relating to the issue will be helpful.

Cheers.

**Comment by pmb399** [comment]
This is strange. In my new experiment install I have no plugins or other language packs installed. This is on a different server running Apache and your php version:

Web Server Software | Apache
MySQL Version | 5.7.25
PHP Version | 5.6.40

Not sure, I just noticed in the information tab that there is supposed to be a newer version out there:
osTicket Version | 1.8-git (?)  Upgrade— 9ae093d is available

But I cloned develop-next yesterday... I will try changing to NGINX later today.

**Comment by JediKev** [comment]
@pmb399 

Don't switch to NGINX as it's not supported. I only use this to test NGINX setups for those people who don't listen to/look at the pre-requisites. But it's the only one where I have the latest PHP installed so I use it to test PHP 7+ issues as well.

Cheers.

**Comment by pmb399** [comment]
Okay, I did some more testing. If you set variables for the custom fields in the latest develop-next version, the error after using the inline editor does not occur and everything works properly. I, however, still get Null instead of empty values in the db after changing any fields in the Manage/Forms/Ticket Details tab.

I also have another question: is it intended that custom fields don't get added to pre-existing tickets and only are visible for tickets that are created later?

Cheers.

**Comment by JediKev** [comment]
@pmb399 

>If you set variables for the custom fields in the latest develop-next version, the error after using the inline editor does not occur and everything works properly. I, however, still get Null instead of empty values in the db after changing any fields in the Manage/Forms/Ticket Details tab.

This was not the case for me. I did not have to put variable names for them. They worked without them.

> is it intended that custom fields don't get added to pre-existing tickets and only are visible for tickets that are created later?

Yes, since the ticket was not created with the field(s) present. You will see it if you edit the entire ticket though.

Cheers.

**Comment by pmb399** [comment]
@JediKev 

I am not sure what is causing that behaviour. I did some more testing today but could neither get it working out of the box nor figure out where the errors are originating from. Sorry.

As I said, setting variable names for the custom fields fixed the problem with the inline editor. Regarding the Null values in the tickets__cdata db, running a query and changing Null to empty strings is a work around for me, especially considering that one does not edit custom fields on a regular basis.

Thanks for the update regarding the pre-existing tickets. Appreciate it!

**Comment by lourdas** [comment]
After upgrading to 1.11 from 1.10.1, I receive DB error 1064, which I figured out happens when the filter condition in the tickets list is empty and you press Enter or click on the find icon. The error is:

    [SELECT COUNT(DISTINCT CASE WHEN  THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE WHEN  THEN A1.`ticket_id` END) AS `q16`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q1`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isanswered` = '0' THEN A1.`ticket_id` END) AS `q2`, COUNT(DISTINCT CASE WHEN A1.`staff_id` IN (30) AND A2.`state` = 'open' AND A1.`staff_id` IN (30) AND A2.`state` = 'open' AND A1.`staff_id` IN (30) THEN A1.`ticket_id` END) AS `q6`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-04-22 00:00:00' AND '2019-04-22 23:59:59' THEN A1.`ticket_id` END) AS `q9`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isanswered` = '1' THEN A1.`ticket_id` END) AS `q3`, COUNT(DISTINCT CASE WHEN A1.`staff_id` IN (30) AND A2.`state` = 'open' AND A1.`staff_id` IN (30) AND A2.`state` = 'open' AND NOT A1.`staff_id` IN (30) THEN A1.`ticket_id` END) AS `q7`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-04-21 00:00:00' AND '2019-04-21 23:59:59' THEN A1.`ticket_id` END) AS `q10`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isoverdue` = '1' THEN A1.`ticket_id` END) AS `q4`, COUNT(DISTINCT CASE WHEN A1.`staff_id` IN (30) AND A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q5`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-04-22 00:00:00' AND '2019-04-28 23:59:59' THEN A1.`ticket_id` END) AS `q11`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' THEN A1.`ticket_id` END) AS `q8`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-04-01 00:00:00' AND '2019-04-30 23:59:59' THEN A1.`ticket_id` END) AS `q12`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-04-01 00:00:00' AND '2019-06-30 23:59:59' THEN A1.`ticket_id` END) AS `q13`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-01-01 00:00:00' AND '2019-12-31 23:59:59' THEN A1.`ticket_id` END) AS `q14` FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost_department` A6 ON (A4.`object_type` = 'D' AND A4.`object_id` = A6.`id`) WHERE (A2.`state` = 'open' AND (A1.`staff_id` = 30 OR A5.`staff_id` = 30)) OR A1.`dept_id` IN (9) OR A6.`id` IN (9)]

    You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE WHEN  THEN A1.`ticket_id`' at line 1<br />
    <br />
    ---- Καταγραφή Σφάλματος (Backtrace) ----<br />
    #0 (αρχικό σημείο)/include/mysqli.php(199): osTicket->logDBError('DB Error #1064', '[SELECT COUNT(D...')<br />
    #1 (αρχικό σημείο)/include/class.orm.php(3454): db_query('SELECT COUNT(DI...', true, true)<br />
    #2 (αρχικό σημείο)/include/class.orm.php(3501): MySqlExecutor->execute()<br />
    #3 (αρχικό σημείο)/include/class.orm.php(2085): MySqlExecutor->getArray()<br />
    #4 (αρχικό σημείο)/include/class.orm.php(2035): HashArrayIterator->{closure}()<br />
    #5 (αρχικό σημείο)/include/class.orm.php(2014): CallbackSimpleIterator->next()<br />
    #6 (αρχικό σημείο)/include/class.orm.php(2023): CallbackSimpleIterator->rewind()<br />
    #7 (αρχικό σημείο)/include/class.orm.php(1695): CallbackSimpleIterator->valid()<br />
    #8 (αρχικό σημείο)/include/class.orm.php(1705): CachedResultSet->fillTo(2147483647)<br />
    #9 (αρχικό σημείο)/include/class.orm.php(1328): CachedResultSet->asArray()<br />
    #10 (αρχικό σημείο)/include/class.orm.php(1351): QuerySet->all()<br />
    #11 (αρχικό σημείο)/include/class.search.php(922): QuerySet->one()<br />
    #12 (αρχικό σημείο)/include/class.search.php(865): SavedQueue::counts(Object(StaffSession), true)<br />
    #13 (αρχικό σημείο)/include/staff/templates/queue-tickets.tmpl.php(96): SavedQueue->getCount(Object(StaffSession))<br />
    #14 (αρχικό σημείο)/scp/tickets.php(525): require_once('/home/www/vhost...')<br />
    #15 (αρχικό σημείο)/scp/index.php(17): require('/home/www/vhost...')<br />
    #16 {main}

Is there a temporary fix for this, since we are overwhelmed with e-mail messages with the DB error?

**Comment by pmb399** [comment]
This looks similar to Issue #4795. Did your upgrade go through without any error messages? Have you checked table `ost_queue` in the database? And, is the syntax in this table correct?

**Comment by lourdas** [comment]
I looked at the issue you refer, but no luck. My ost_queue table looks like this:

![ost_queue](https://user-images.githubusercontent.com/397916/56487942-88fbc300-64e5-11e9-9c28-7b359228229a.png)

**Comment by JediKev** [comment]
@lourdas 

Please do not hijack other people's thread with separate issues. Either post on an issue similar to yours that is still Open, or if none create your own issue report.

I'll go ahead and answer your here though:
All you have to do is go to the database, go to the `ost_queue` table, and delete the records with IDs of `15` and `16`.

Cheers.

**Comment by lourdas** [comment]
@JediKev Sorry for hijacking the other thread. I was just frustrated at the moment with the number of e-mail notifications about the DB error. I turned off the e-mail notifications, but the error still persisted, which lead me to reverting back to 1.10.1.

I will try to upgrade again to 1.11 and see what happens. Thanks.

**Comment by milytre** [comment]
Hi everyone,

When I tried to Inline-edit a custom field (date type) the below error message was found. The intended date was updated in the ticket but everytime the Inline Edit feature is used the error would be sent to the admin email.

How to solve this problem? Thank you.

edit: This installation was upgraded from 1.9 to 1.14.
```
Server Information
--
osTicket Version | v1.14.2 (cba6035) —  Up to date
Web Server Software | Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.4.6
MySQL Version | 10.4.11
PHP Version | 7.4.6
```

```
DB Error #1054
[INSERT INTO `ost_ticket__cdata` SET `field`='2020-05-28 00:00:00 CST', `ticket_id`= 201 ON DUPLICATE KEY UPDATE `field`='2020-05-28 00:00:00 CST'] Unknown column 'field' in 'field list'

---- Backtrace ----
#0 C:\xampp\htdocs\support\include\mysqli.php(200): osTicket->logDBError('DB Error #1054', '[INSERT INTO `o...')
#1 C:\xampp\htdocs\support\include\class.dynamic_forms.php(334): db_query('INSERT INTO `os...')
#2 C:\xampp\htdocs\support\include\class.dynamic_forms.php(346): DynamicForm::updateDynamicDataView(Object(DynamicFormEntryAnswer), Array)
#3 C:\xampp\htdocs\support\include\class.signal.php(98): DynamicForm::updateDynamicFormEntryAnswer(Object(DynamicFormEntryAnswer), Array)
#4 C:\xampp\htdocs\support\include\class.orm.php(684): Signal::send('model.updated', Object(DynamicFormEntryAnswer), Array)
#5 C:\xampp\htdocs\support\include\class.dynamic_forms.php(1458): VerySimpleModel->save(true)
#6 C:\xampp\htdocs\support\include\class.forms.php(1385): DynamicFormEntryAnswer->save(true)
#7 C:\xampp\htdocs\support\include\class.ticket.php(3777): FormField->save(true)
#8 C:\xampp\htdocs\support\include\ajax.tickets.php(658): Ticket->updateField(Object(SimpleForm), Array)
#9 C:\xampp\htdocs\support\include\class.dispatcher.php(145): TicketsAjaxAPI->editField('201', '58')
#10 C:\xampp\htdocs\support\include\class.dispatcher.php(38): UrlMatcher->dispatch('201/field/58/ed...', Array)
#11 C:\xampp\htdocs\support\include\class.dispatcher.php(120): Dispatcher->resolve('201/field/58/ed...', Array)
#12 C:\xampp\htdocs\support\include\class.dispatcher.php(38): UrlMatcher->dispatch('/tickets/201/fi...', NULL)
#13 C:\xampp\htdocs\support\scp\ajax.php(311): Dispatcher->resolve('/tickets/201/fi...')
#14 {main}

Log Date: Thursday, May 28, 2020 at 5:13 PM
```

**Comment by JediKev** [comment]
@milytre 

Check your Ticket Details Form and see if the Custom Field has a variable name. If not, add one and retest.

Cheers.

**Comment by milytre** [comment]
> 
> 
> @milytre
> 
> Check your Ticket Details Form and see if the Custom Field has a variable name. If not, add one and retest.
> 
> Cheers.

Added all missing variables and yes problem solved. Thank you very much!

**Comment by ymachuca** [comment]
Error:
[INSERT INTO `ost_user__cdata` SET `notes`='', `user_id`= 14 ON DUPLICATE KEY UPDATE `notes`='']
Unknown column 'notes' in 'field list'<br /> <br />

That columns "notes" was not part of mysql table ost_user__ccdata:

MariaDB [osticket_db]> select * from ost_user__cdata;
+---------+-------+
| user_id | email |
+---------+-------+
|       1 | NULL  |
+---------+-------+
1 row in set (0.000 sec)

We deleted Internal Notes field on:
Admin Panel
Manage
Forms
Contact Information

Then we add it again after that mysql table ost_user__cdata show all it columns including "notes"
MariaDB [osticket_db]> select * from ost_user__cdata;
+---------+-------+------+-----------------+-------+
| user_id | email | name | phone           | notes |
+---------+-------+------+-----------------+-------+
|       1 | NULL  | NULL | NULL            | NULL  |
|       2 | NULL  | NULL | XXXXXXX     | NULL  |
2 rows in set (0.000 sec)

We are not getting the error

**Comment by JediKev** [comment]
@ymachuca 

You will need to go to the Contact Information Form and ensure there is a Notes field with the variable name of `notes`. Then you can go to the database, drop/delete the `ost_user__cdata` table, add a fake/dummy field to the Contact Information Form, save changes, delete the fake/dummy field, and the CDATA table will be regenerated. This should then add the `notes` column in the CDATA table and avoid those errors.

Cheers.

**Comment by ymachuca** [comment]
@JediKev got it, a lot of thank you.
