### ISSUE TITLE
Unable to upload some file extensions in osTicket 1.16.6

### ISSUE THREAD

**Issue by Philippe34** [osTicket/osTicket#6498]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
I did not try
* [ ] Do you have any errors in the PHP error log, or javascript console?
I can't see any errors in the PHP error log, only in javascript console
* [ ] Did you check the [osTicket forums](https://forum.osticket.com/)?
yes
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
yes

### Description

After updating osticket 1.16.5 to 1.16.6, I can only upload a few file of attachments
I can upload PDF, TXT, JPEG files but not ZIP or STL file format.

### Steps to Reproduce

1. Open a new ticket
2. Add ZIP file

**Expected behavior:** 
It should be uploaded as it can be done with osticket 1.16.5

**Actual behavior:** 
![image](https://user-images.githubusercontent.com/12435553/226915316-ef34b81d-7eb7-4529-8533-a94acbe47560.png)

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.
![image](https://user-images.githubusercontent.com/12435553/226916213-2462a47b-7743-4a8b-a1b1-fefcc24ce871.png)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

osticket runs on Rocky Linux 8 

Logs when I try to upload a ZIP file :
"POST /scp/ajax.php/form/upload/36 HTTP/1.1" 500 12 "https://scei.domain.fr/scp/tickets.php?a=open&uid=5" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0" TLSv1.3 TLS_AES_128_GCM_SHA256

Logs when I upload a PDF file :
"POST /ajax.php/form/upload/36 HTTP/1.1" 200 10 "https://scei.domain.fr/open.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0" TLSv1.3 TLS_AES_128_GCM_SHA256

With the Firefox developper tools:
![image](https://user-images.githubusercontent.com/12435553/226917287-31f37622-c72b-4f95-aa80-9b36c8c03c15.png)
![image](https://user-images.githubusercontent.com/12435553/226917314-9f55ff38-6583-4c52-b881-97d87cef023c.png)

Can you also reproduce this issue in 1.16.6 ?

Thanks !

**Comment by JediKev** [comment]
@Philippe34 

Please do a search before creating an issue. This is already fixed here:
- https://github.com/osTicket/osTicket/pull/6495

Cheers.

**Comment by Philippe34** [comment]
@JediKev 
Yes I saw this issue.
I did the change as it was suggested in the class.forms.php, but it did not solve the problem.

**Comment by Philippe34** [comment]
Can you try to upload a ZIP file please ?

Cheers

**Comment by JediKev** [comment]
@Philippe34 

Just tested a ZIP upload with v1.16.6 and the patch applied and it worked right away. You will need to double check your changes and ensure you applied them adequately. Also, you may need to restart your webserver and/or PHP-FPM (if you're running it).

Cheers.

**Comment by Philippe34** [comment]
Thanks for your test.
For you, ZIP upload works.
For me, it's not the case.

So I replace the osTicket 1.16.6 class.forms.php file by the osTicket 1.16.5 class.forms.php, and it works well with ZIP

I put the osTicket 1.16.6 patched back
I try again STL file, and now it works !
![image](https://user-images.githubusercontent.com/12435553/226946855-f80ad73c-7afa-496c-99d7-98d4c29640b5.png)

Only ZIP files can not be uploaded for me.
![image](https://user-images.githubusercontent.com/12435553/226954150-f6f5b352-0f5f-4836-b5e5-304f15fe6c04.png)


I don't know why this code added in osTicket 1.16.6 is only an issue for me :

```
static function isValidFile($file) {
        // Make sure mime type is valid
        if (!empty($file['type']) && strcasecmp(FileObject::mime_type($file['tmp_name']),
                $file['type']) !== 0)
            return false;
```

**Comment by JediKev** [comment]
@Philippe34 

Can you provide an example ZIP that cannot be uploaded?

Cheers.

**Comment by Philippe34** [comment]
Yes. 
Here is a simple ZIP file I have done with Powerarchiver
[test.zip](https://github.com/osTicket/osTicket/files/11041816/test.zip)

Thank you.

**Comment by JediKev** [comment]
@Philippe34 

That one uploaded just fine for me:
<img width="529" alt="Screen Shot 2023-03-22 at 10 37 01" src="https://user-images.githubusercontent.com/11823401/226957331-407145c9-03bc-4302-9e07-0fc2fb110393.png">

Can you try downloading the ZIP from your post above and retry the upload in osTicket? I'm wondering if the MIME type was messed up and upload/download fixed it?

Cheers.

**Comment by Philippe34** [comment]
@JediKev 
I tried downloading the ZIP from the post and unfortunally it's the same problem.
I tried with Firefox, Chrome.

Could you post your ZIP so that I can test as well ?

**Comment by JediKev** [comment]
@Philippe34 

I don't have any I can share with the public but I'm just using any and every ZIP I have. All of them work including your example above. From here it looks like you will need to do some debugging. Go to `include/class.forms.php`, above the `if()` statement at the top of the `isValidFile` method add `var_dump($file['type']);die;`, save the changes, go back to your browser, Right Click + Inspect the page, go to the **Network** tab, upload a ZIP, and look at the response for what the var_dump returns.

Cheers.

**Comment by Philippe34** [comment]
I did what you said and the response is:
string(28) "application/x-zip-compressed"

**Comment by JediKev** [comment]
@Philippe34 

Do you have the `php-fileinfo` extension installed and enabled? You can look at your **Admin Panel > Dashboard > Information** page to see if it shows checkmark (installed/enabled) or an "x" (not installed/not enabled) next to fileinfo.

Cheers.

**Comment by Philippe34** [comment]
@JediKev
I have the php-fileinfo extension installed via the php-common package. It is enabled.
I added this code:
```
var_dump($file['type']);
var_dump(FileObject::mime_type($file['tmp_name'])); die;
```

When I upload a ZIP file, the response is:
![image](https://user-images.githubusercontent.com/12435553/227143594-ac6b82c3-205f-4367-bce4-fdd2f9cce729.png)

So it explains why the strcasecmp returns false

If I upload a PDF file, it returns the same thing:
![image](https://user-images.githubusercontent.com/12435553/227144138-e6002c58-e233-4a1f-9aa7-caa24a53c31c.png)

So it can be uploaded

**Comment by JediKev** [comment]
@Philippe34 

So weird..mine shows the correct MIME type but yours shows `application/octet-stream`. I'll have to dig deeper to see how it's doing that.

Cheers.

**Comment by Philippe34** [comment]
@JediKev 
I've found this bug in PHP 8.0
https://bugs.php.net/bug.php?id=80887

**Comment by JediKev** [comment]
@Philippe34 

Well I’ve noticed an inconsistency with another unrelated file type but this might be the difference in this particular case as I’m using PHP 8.1 and do not get the same issue with ZIP files specifically. Try upgrading PHP to 8.1, install the php-fileinfo extension, and retest with your ZIP.

Cheers.

**Comment by Philippe34** [comment]
@JediKev

With osTicket 1.16.5, I had already tried to upgrade to PHP 8.1, but when I did this, I could not be authenticated with LDAP.
It was a big problem. I saw in the forum that a lot of people had this problem when they upgraded to PHP 8.1.
I don't understand if this was solved in osTicket 1.16.6 or 1.17.3 ?
Do you know ?

**Comment by JediKev** [comment]
@Philippe34 

I do not think so, no as I could never replicate the issue. I only have OpenLDAP which does not use MSAD schema. The issue is with the MSAD schema specifically. With this being said, this is still on my list to look into. I just need to get an actual AD server and run through debugging.

Cheers.

**Comment by Philippe34** [comment]
I use openLDAP , not MSAD

**Comment by JediKev** [comment]
@Philippe34 

Oh, well then there should be no issues.

Cheers.

**Comment by Philippe34** [comment]
@JediKev 
Thanks for your answer.
I have to see with the osTicket manager to do again the PHP upgrade.
Maybe the next week.

Best regards

**Comment by Philippe34** [comment]
@JediKev

Before upgrading PHP, I have fixed this PHP bug with this patch:

```
if (!empty($file['type']) && strcasecmp(FileObject::mime_type($file['tmp_name']),
                $file['type']) !== 0) {
                // BUG fileinfo() with ZIP file in PHP 8.0, refer to : https://bugs.php.net/bug.php?id=80887
                if ( version_compare(PHP_VERSION, '8.1.0', '<') && preg_match("/zip/", $file['type']) && strcasecmp(FileObject::mime_type($file['tmp_name']), "application/octet-stream" == 0) ) {
                    ; // noop
                } else return false;
        }
```
I can now upload ZIP files
![image](https://user-images.githubusercontent.com/12435553/227467821-bbfa6fbe-cdb6-4575-bbfc-61a6d6b8d86d.png)

What do you think ?

**Comment by clicit** [comment]
@Philippe34 thanks this worked for me as a temporary fix also. Additionally, I had to adapt your code because the same problem exists with CSS files, where $file['type'] is text/css but mime_type returns text/plain.

**Comment by Philippe34** [comment]
@clicit
Great !
