### ISSUE TITLE
IMAP TLS not working

### ISSUE THREAD

**Issue by tbswork1** [osTicket/osTicket#6527]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
no
* [ ] Do you have any errors in the PHP error log, or javascript console?
no

* [ ] Did you check the [osTicket forums](https://forum.osticket.com/)?
no
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
no

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
Follow [doc](https://docs.osticket.com/en/latest/Admin/Emails/Emails.html)
Unable to save IMAP setting under Remote Mailbox

[Description of the bug or feature]

### Steps to Reproduce

1. Admin panel -> Add new email -> Remote Mailbox
3. Configure IMAP, click 'Config'
4. Put in email address and password, save. 

**Expected behavior:** [What you expected to happen]
IMAP setting saved.

**Actual behavior:** [What actually happened]
Shows 'loading' and never returns.

### Versions
1.17.3-2-g4e570b53 (4e570b5) 
Apache/2.4.41 (Ubuntu)

**Comment by Raito00** [comment]
In my case i fixed like this:
Hostname: ssl://my.mailserver.com
Port number: 993

**Comment by tbswork1** [comment]
It's the same whether there is a prefix of ssl:// or not. It's still not getting emails. At the server end there is no related log.

**Comment by JediKev** [comment]
@tbswork1 

This is better suited for our [Community Supported Forum](https://forum.osticket.com). GitHub is a place to report bugs, request new features, or submit pull requests; it is not a support forum. When you have an issue please start by creating a discussion on the Forum. There we can go through the issue and if we determine it’s an actual bug then you can open an Issue here. 

With that being said, I will close this so you can create a discussion on the Forum. I will however provide a quick response since we are already here. You need to check your logs (general server logs, webserver error logs, PHP error logs, MySQL/MariaDB error logs, osTicket System Logs, Browser Console logs, etc.) for any related errors.

Cheers.
