### ISSUE TITLE
 The used SELECT statements have a different number of columns

### ISSUE THREAD

**Issue by Mike-Benoit** [osTicket/osTicket#6565]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

Receive the following DB error report:

[SELECT COUNT(*) FROM (SELECT A1.`ticket_id` FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost_thread` A6 ON (A1.`ticket_id` = A6.`object_id` AND A6.`object_type` = 'C') LEFT JOIN `ost_thread_referral` A7 ON (A6.`id` = A7.`thread_id`) LEFT JOIN `ost_staff` A8 ON (A7.`object_type` = 'S' AND A7.`object_id` = A8.`staff_id`) LEFT JOIN `ost_team` B0 ON (A4.`object_type` = 'E' AND A4.`object_id` = B0.`team_id`) LEFT JOIN `ost_team` B1 ON (A7.`object_type` = 'E' AND A7.`object_id` = B1.`team_id`) LEFT JOIN `ost_department` B2 ON (A4.`object_type` = 'D' AND A4.`object_id` = B2.`id`) LEFT JOIN `ost_department` B3 ON (A7.`object_type` = 'D' AND A7.`object_id` = B3.`id`) LEFT JOIN `ost_user` B4 ON (A1.`user_id` = B4.`id`) WHERE ((A2.`state` = 'open' AND (A1.`staff_id` = 9 OR A5.`staff_id` = 9 OR A6.`object_type` = 'C' AND A8.`staff_id` = 9 OR A1.`team_id` IN (2) OR B0.`team_id` IN (2) OR A6.`object_type` = 'C' AND B1.`team_id` IN (2))) OR A1.`dept_id` IN (1) OR B2.`id` IN (1) OR A6.`object_type` = 'C' AND B3.`id` IN (1)) AND B4.`name` LIKE 'sneha%' UNION ALL (SELECT B5.`address` AS `user__default_email__address`, B6.`subject` AS `cdata__subject`, B4.`name` AS `user__name`, A1.`ticket_id` AS `ticket_id`, A3.`id` AS `thread__id`, A1.`flags` AS `flags`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tickets`, COUNT(DISTINCT B7.`id`) AS `tasks`, COUNT(DISTINCT B8.`id`) AS `collaborators`, COUNT(DISTINCT C0.`id`) AS `entries` FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost_thread` A6 ON (A1.`ticket_id` = A6.`object_id` AND A6.`object_type` = 'C') LEFT JOIN `ost_thread_referral` A7 ON (A6.`id` = A7.`thread_id`) LEFT JOIN `ost_staff` A8 ON (A7.`object_type` = 'S' AND A7.`object_id` = A8.`staff_id`) LEFT JOIN `ost_team` B0 ON (A4.`object_type` = 'E' AND A4.`object_id` = B0.`team_id`) LEFT JOIN `ost_team` B1 ON (A7.`object_type` = 'E' AND A7.`object_id` = B1.`team_id`) LEFT JOIN `ost_department` B2 ON (A4.`object_type` = 'D' AND A4.`object_id` = B2.`id`) LEFT JOIN `ost_department` B3 ON (A7.`object_type` = 'D' AND A7.`object_id` = B3.`id`) LEFT JOIN `ost_user` B4 ON (A1.`user_id` = B4.`id`) LEFT JOIN `ost_user_email` B5 ON (B4.`default_email_id` = B5.`id`) LEFT JOIN `ost_ticket__cdata` B6 ON (A1.`ticket_id` = B6.`ticket_id`) LEFT JOIN `ost_task` B7 ON (A1.`ticket_id` = B7.`object_id`) LEFT JOIN `ost_thread_collaborator` B8 ON (A3.`id` = B8.`thread_id`) LEFT JOIN `ost_thread_entry` C0 ON (A3.`id` = C0.`thread_id`) JOIN (SELECT COALESCE(Z3.`object_id`, Z5.`ticket_id`, Z8.`ticket_id`) as `ticket_id`, Z1.relevance FROM (SELECT Z1.`object_id`, Z1.`object_type`, MATCH (Z1.title, Z1.content) AGAINST ('sneha' IN NATURAL LANGUAGE MODE) AS `relevance` FROM `ost__search` Z1 WHERE MATCH (Z1.title, Z1.content) AGAINST ('sneha' IN NATURAL LANGUAGE MODE) ORDER BY relevance DESC) Z1 LEFT JOIN `ost_thread_entry` Z2 ON (Z1.`object_type` = 'H' AND Z1.`object_id` = Z2.`id`) LEFT JOIN `ost_thread` Z3 ON (Z2.`thread_id` = Z3.`id` AND (Z3.`object_type` = 'T' OR Z3.`object_type` = 'C')) LEFT JOIN `ost_ticket` Z5 ON (Z1.`object_type` = 'T' AND Z1.`object_id` = Z5.`ticket_id`) LEFT JOIN `ost_user` Z6 ON (Z6.`id` = Z1.`object_id` and Z1.`object_type` = 'U') LEFT JOIN `ost_organization` Z7 ON (Z7.`id` = Z1.`object_id` AND Z7.`id` = Z6.`org_id` AND Z1.`object_type` = 'O') LEFT JOIN `ost_ticket` Z8 ON (Z8.`user_id` = Z6.`id`)) Z1 WHERE ((A2.`state` = 'open' AND (A1.`staff_id` = 9 OR A5.`staff_id` = 9 OR A6.`object_type` = 'C' AND A8.`staff_id` = 9 OR A1.`team_id` IN (2) OR B0.`team_id` IN (2) OR A6.`object_type` = 'C' AND B1.`team_id` IN (2))) OR A1.`dept_id` IN (1) OR B2.`id` IN (1) OR A6.`object_type` = 'C' AND B3.`id` IN (1)) AND A1.`ticket_id` = Z1.`ticket_id` GROUP BY B5.`address` ORDER BY Z1.relevance  LIMIT 25) LIMIT 25) __]

The used SELECT statements have a different number of columns<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(211): osTicket->logDBError()<br />
#1 (root)/include/class.orm.php(3482): db_query()<br />
#2 (root)/include/class.orm.php(3538): MySqlExecutor->execute()<br />
#3 (root)/include/class.orm.php(2964): MySqlExecutor->getRow()<br />
#4 (root)/include/class.orm.php(1381): MySqlCompiler->compileCount()<br />
#5 (root)/include/ajax.tickets.php(102): QuerySet->count()<br />
#6 (root)/include/class.dispatcher.php(153): TicketsAjaxAPI->lookup()<br />
#7 (root)/include/class.dispatcher.php(40): UrlMatcher->dispatch()<br />
#8 (root)/include/class.dispatcher.php(122): Dispatcher->resolve()<br />
#9 (root)/include/class.dispatcher.php(40): UrlMatcher->dispatch()<br />
#10 (root)/scp/ajax.php(327): Dispatcher->resolve()<br />
#11 {main}

Got error 'PHP message: PHP Fatal error:  Uncaught InconsistentModelException: Unable to prepare query:  SELECT COUNT(*) FROM (SELECT A1.`ticket_id` FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost_thread` A6 ON (A1.`ticket_id` = A6.`object_id` AND A6.`object_type` = 'C') LEFT JOIN `ost_thread_referral` A7 ON (A6.`id` = A7.`thread_id`) LEFT JOIN `ost_staff` A8 ON (A7.`object_type` = 'S' AND A7.`object_id` = A8.`staff_id`) LEFT JOIN `ost_team` B0 ON (A4.`object_type` = 'E' AND A4.`object_id` = B0.`team_id`) LEFT JOIN `ost_team` B1 ON (A7.`object_type` = 'E' AND A7.`object_id` = B1.`team_id`) LEFT JOIN `ost_department` B2 ON (A4.`object_type` = 'D' AND A4.`object_id` = B2.`id`) LEFT JOIN `ost_department` B3 ON (A7.`object_type`...', referer: https://helpdesk.timetrex.com/scp/tickets.php?queue=24

### Versions

1.17-git

**Comment by JediKev** [comment]
@Mike-Benoit 

Your report says `1.17-git`. At what commit? Have you tried using an officially packaged release from our website? We released v1.17.4 and v1.18 yesterday.

Is this error caused by a User Lookup? If so, do you have the LDAP plugin installed?

What version of PHP are you running?

Cheers.

**Comment by Mike-Benoit** [comment]
We updated to latest GIT as of yesterday evening and the issue persists. However we haven't discovered the exact procedure to replicate the problem. We just know we received the above errors about 20x per day given regular usage. 

Because the errors come in batches of about 4-5 per minute, and based on the error message, we believe its related to type-ahead search functionality. 

We do not use an LDAP plugin. PHP is v8.1.20.

**Comment by Mike-Benoit** [comment]
Turns out this was related to a few bug fixes and improvements we implemented in v1.15, which still aren't fixed in v1.17. Once we carried them forward it resolved this.

**Comment by JediKev** [comment]
@Mike-Benoit 

Care to share what you mean?

Cheers.
